### ISSUE TITLE
Raspberry Pi error with Inkscape 0.92

### ISSUE THREAD

**Issue by qroft** [mireq/inkscape-export-selection-as-svg#2]
The plugin looks absolutely promising, but it does not work under my Raspberry Pi 400.
This might be that "Buster" on Pi only uses Inkscape 0.92 at the moment.
This is my error:
`  File "export_selection.py", line 74
    template.attrib['viewBox'] = f'0 0 {width} {height}'
                                                       ^
SyntaxError: invalid syntax
`

**Comment by mireq** [comment]
Hello, i don't think, that supporting 6 year old python is good idea. You can try replace strings if you want, but i don't think, it will work.

**Comment by qroft** [comment]
You are absolutely correct. Thanks for the hint!
